### ISSUE TITLE
dukop favicon

### ISSUE THREAD

**Issue by ronan-mch** [dukop/duk_op#312]
Hej @Siggik - kan vi have en favicon?

**Comment by Siggik** [comment]
Det synes jeg lyder som en go idé! Logoet gjort lille? Kan du gøre det? Eller skal jeg lokke Kris til det? Hvis, hvilke specs skal det ha?

**Comment by ronan-mch** [comment]
prøve at høre om favicon siger hende noget, wikipedia siger 16x16 pixels.
jeg går ud far at det baseres på loget.

**Comment by dotnetCarpenter** [comment]
@ronan-mch uuuuuuuuuuuuaaaaaa - det var dengang for lang lang tid siden da alting var simpelt. Se her: https://github.com/audreyr/favicon-cheat-sheet

Men heldigvis har vi seje værktøjer: http://www.favicomatic.com
Du skal bruge en 310x310px størrelse.

**Comment by ronan-mch** [comment]
bump - sker der noget med favicon?

**Comment by dotnetCarpenter** [comment]
Her er alle favicons mand kan drømme om via favicomatic.com, baseret på logoet.
[dukop_favicon.zip](https://github.com/ronan-mch/det_sker/files/219177/dukop_favicon.zip)
*billede burde have været 310px/310px men er 400px/131px, så det er mast lidt sammen*

HTML til faviconer:
```html
<link rel="apple-touch-icon-precomposed" sizes="57x57" href="apple-touch-icon-57x57.png" />
<link rel="apple-touch-icon-precomposed" sizes="114x114" href="apple-touch-icon-114x114.png" />
<link rel="apple-touch-icon-precomposed" sizes="72x72" href="apple-touch-icon-72x72.png" />
<link rel="apple-touch-icon-precomposed" sizes="144x144" href="apple-touch-icon-144x144.png" />
<link rel="apple-touch-icon-precomposed" sizes="60x60" href="apple-touch-icon-60x60.png" />
<link rel="apple-touch-icon-precomposed" sizes="120x120" href="apple-touch-icon-120x120.png" />
<link rel="apple-touch-icon-precomposed" sizes="76x76" href="apple-touch-icon-76x76.png" />
<link rel="apple-touch-icon-precomposed" sizes="152x152" href="apple-touch-icon-152x152.png" />
<link rel="icon" type="image/png" href="favicon-196x196.png" sizes="196x196" />
<link rel="icon" type="image/png" href="favicon-96x96.png" sizes="96x96" />
<link rel="icon" type="image/png" href="favicon-32x32.png" sizes="32x32" />
<link rel="icon" type="image/png" href="favicon-16x16.png" sizes="16x16" />
<link rel="icon" type="image/png" href="favicon-128.png" sizes="128x128" />
<meta name="application-name" content="&nbsp;"/>
<meta name="msapplication-TileColor" content="#FFFFFF" />
<meta name="msapplication-TileImage" content="mstile-144x144.png" />
<meta name="msapplication-square70x70logo" content="mstile-70x70.png" />
<meta name="msapplication-square150x150logo" content="mstile-150x150.png" />
<meta name="msapplication-wide310x150logo" content="mstile-310x150.png" />
<meta name="msapplication-square310x310logo" content="mstile-310x310.png" />
```

**Comment by ronan-mch** [comment]
jeg synes ikke det ser særlig godt ud med logo-en på denne størrelse,
derfor kunne jeg godt tænke mig at designeren lavede en ikon ud fra
billedet der kunne se godt ud som en favicon.

**Comment by dotnetCarpenter** [comment]
jep, i 310px X 310px - jeg lavede bare en hurtig demo til at motivere designeren :dancers:

**Comment by Siggik** [comment]
Jeg skriver det på min to do liste.

**Comment by Siggik** [comment]
jeg har gjort et forsøg:

![dukop](https://cloud.githubusercontent.com/assets/7570153/18889772/b90a1566-84fe-11e6-9109-6f351227f64e.png)

**Comment by Siggik** [comment]
@tadoh , jeg håber ikke du allerede havde fået et lavet?

**Comment by tadoh** [comment]
Nej det havde jeg ikke. Hvordan ser den ud i browseren? Kan den testes?

-------- Original message --------

**Comment by benjaoming** [comment]
Jeg laver lige noget i Nginx i hvert fald, så kan vi også lige få tilføjet det dér html...

**Comment by benjaoming** [comment]
Done! :)

![image](https://user-images.githubusercontent.com/374612/36176303-74f300c6-1112-11e8-99d4-185432b17ab6.png)
