### ISSUE TITLE
Bedre facebook metadata for forside deling 

### ISSUE THREAD

**Issue by Siggik** [dukop/duk_op#386]
Når man deler forsiden af dukop.dk på facebook, så er det altid billedet af et udløbet event der blir vist og en tekst fra et andet udløbet event der blir vist. Kunne være optur, hvis det var logoet. Og en mere general tekst.

**Comment by dotnetCarpenter** [comment]
@ronan-mch Du ved det sikkert, men det er `<meta property="og:...` meta tags som skal enten have det samme text/billede som event siden eller bare statisk tekst og dukop logoet.
http://opengraphprotocol.org/

**Comment by ronan-mch** [comment]
ja, dem har vi på event siderne. Vi har bare ikke nogen på forsiden så
Facebook laver en best guess og sikkert laver nogle caching som fører til
problemet her.

**Comment by Siggik** [comment]
Var på vej ind at oprette dette issue, men det var her allrede. AKA Kunne stadig være fedt! :)

**Comment by benjaoming** [comment]
Så er det fikset på det gamle site, laver noget nyt til beta
