### ISSUE TITLE
Når man redigerer start time, rykker end time sig

### ISSUE THREAD

**Issue by tadoh** [dukop/duk_op#393]
Jeg skal redigere start time i min event.
Når jeg gør det, rykker det også end time til det nye start time, så jeg manuelt skal ændre end time igen til den gamle (eller anden) tid. Hvis man ønskede at rykke også det, vil man nok selv tjekke det, når man er logget ind for at redigere tid, til gengæld risikerer man at overse at end time har ændret sig, da det er counterintuitive at den skulle rykke (og i det mindste nogle ekstra, unødvendige clicks).

**Comment by benjaoming** [comment]
Hey! Efter den gamle kalender-widget er fjernet, og det hele bare er dropdowns, er der ikke det problem mere :) På beta vil det heller ikke være et problem, vi lader bare være med at lave noget fjollet javascript voodoo.
