### ISSUE TITLE
når man opretter gentagende events fremstår tiden 2 timer senere på forsiden, end den man taster ind på "opret event siden""

### ISSUE THREAD

**Issue by Siggik** [dukop/duk_op#413]
Sådan er det med alle de gentagene events, som nu er meget få. jeg gir den en skalle med at få folk til oprette dem igen, når fejlen er rettet.

**Comment by Siggik** [comment]
Lige en reminder. Kunne være fedt at få fiket. Det er ret besværligt, for jeg skal ind maunelt og rette, men også greje om det er forkert eller rigtigt det, de er endt med at få sat som tid. Lidt af et gravearbejde. Der kommer jo også snart vintertid. Er der styr på den? :)

**Comment by Siggik** [comment]
Denne bug er der stadig, Nu kun med en time forkert. 

Når man går ind og retter fejlen, så virker det fint. Det er kun når man oprettet eventet første gang, at fejlen er der.

Overgangen til vintertid ser ud til at være gået smooth! Kun den her gamle bug tilbage :)

**Comment by benjaoming** [comment]
rettet og live! test gerne @Siggik !

**Comment by Siggik** [comment]
Ser ud til at virke perfekt!
