### ISSUE TITLE
Engelsk beskrivelsesfelt

### ISSUE THREAD

**Issue by punkpanda666** [dukop/duk_op#464]
Kan der blive lavet et felt til hhv. dansk og engelsk beskrivelse?
Så kan vi undgå at der er beskrivelser på 2 sprog i events og folk der bruger siden på engelsk vil hurtigere kunne læse noget de forstår

**Comment by Siggik** [comment]
Ja, tænk er jeg gir mening. Spørgsmålet er hvor vi viser det, når der ikke er en engelsk eller dansk tekst? Automatisk, det sprog der findes? Hvad med svensk?
